# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gateway < Formula
  desc "A robust cloud-native AI Gateway"
  homepage "https://github.com/missingstudio/gateway"
  version "0.0.1"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Darwin_arm64.tar.gz"
      sha256 "171190d1d15a67bd174aa01666d9cde7aa555417c8f104315f5466870ec09cca"

      def install
        bin.install "gateway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Darwin_x86_64.tar.gz"
      sha256 "9485e6f9fef6f0d21a985f3f41775cb8ab1717c3671c48700e2b7477920cb739"

      def install
        bin.install "gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Linux_arm64.tar.gz"
      sha256 "e428288c42ea437aeb8583530daf132a31503670dd4b92fdaf2982ecb786c445"

      def install
        bin.install "gateway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Linux_x86_64.tar.gz"
      sha256 "8d150bdf51f4c1b0d51108eb06549ffeebf88f05b466dcb2ab9e2bcf43fc6674"

      def install
        bin.install "gateway"
      end
    end
  end
end
