# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gateway < Formula
  desc "A robust cloud-native AI Gateway"
  homepage "https://github.com/missingstudio/gateway"
  version "0.0.1"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Darwin_arm64.tar.gz"
      sha256 "59494ff888374d1be3f11f58b57bc4702800ff017226f4cac4f7864799fffda9"

      def install
        bin.install "gateway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Darwin_x86_64.tar.gz"
      sha256 "590acb72bcff7a5c1a048afa3e2b5a5352bb5af87296305e2d471072144c2946"

      def install
        bin.install "gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Linux_arm64.tar.gz"
      sha256 "e192f8d03bb938cd9538c24328df3946ab8c47b1220f31b6cd3c95e0e0e136cc"

      def install
        bin.install "gateway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Linux_x86_64.tar.gz"
      sha256 "4e2d8370a6fd2bca2b80036f83a86ab68f28dfb9b351185ef0d1e0db1b3caaea"

      def install
        bin.install "gateway"
      end
    end
  end
end
