# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gateway < Formula
  desc "A robust cloud-native AI Gateway"
  homepage "https://github.com/missingstudio/gateway"
  version "0.0.1"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Darwin_arm64.tar.gz"
      sha256 "8de45ba5c407c9d08baac5ae9e14dbcdb7d32f07ffd06af5e7221708fa9916b9"

      def install
        bin.install "gateway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Darwin_x86_64.tar.gz"
      sha256 "c6034afc3dceba911d39e85d1c0d80284f4e389431e5f66c0902bf28aeb2fa4d"

      def install
        bin.install "gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Linux_arm64.tar.gz"
      sha256 "b6130392aa94de58f22e211925322ae33e8660b52b3c15ab586c3cb23e815f9d"

      def install
        bin.install "gateway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/missingstudio/gateway/releases/download/v0.0.1/gateway_Linux_x86_64.tar.gz"
      sha256 "2008a45dce697ab44caae7375ddc74606405873629773279bad3f32e999cbc33"

      def install
        bin.install "gateway"
      end
    end
  end
end
